# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewEmojiGifTextEdit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewEmojiGifTextEdit
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'FLAnimatedImage'
  
end
